import type { Appointment } from "@/src/types/appointments.types";

export const mockAppointments: Appointment[] = [
  {
    id: "a1",
    createdAt: "2025-12-10",
    scheduledAt: "2025-12-13 10:30",
    city: "Barranquilla",
    clinicName: "Happy Paws Clinic",
    petOwnerName: "Ariana Barreto",
    service: "Consulta",
    status: "CONFIRMED",
    flagged: false,
  },
  {
    id: "a2",
    createdAt: "2025-12-12",
    scheduledAt: "2025-12-13 14:00",
    city: "Bogotá",
    clinicName: "VetCare 24/7",
    petOwnerName: "Carlos Pérez",
    service: "Emergencia",
    status: "PROBLEMATIC",
    flagged: true,
  },
  {
    id: "a3",
    createdAt: "2025-12-05",
    scheduledAt: "2025-12-12 09:00",
    city: "Medellín",
    clinicName: "Animalia Center",
    petOwnerName: "María Gómez",
    service: "Grooming",
    status: "COMPLETED",
    flagged: false,
  },
  {
    id: "a4",
    createdAt: "2025-12-11",
    scheduledAt: "2025-12-14 16:15",
    city: "Cali",
    clinicName: "CostaVet",
    petOwnerName: "Sebastián Ruiz",
    service: "Consulta",
    status: "PENDING",
    flagged: false,
  },
  {
    id: "a5",
    createdAt: "2025-12-09",
    scheduledAt: "2025-12-13 11:00",
    city: "Bogotá",
    clinicName: "VetCare 24/7",
    petOwnerName: "Laura Torres",
    service: "Consulta",
    status: "CANCELED",
    flagged: false,
  },
];


export const mockProblematicAppointments: Appointment[] = [
  {
    id: "a2",
    createdAt: "2025-12-12",
    scheduledAt: "2025-12-13 14:00",
    city: "Bogotá",
    clinicName: "VetCare 24/7",
    petOwnerName: "Carlos Pérez",
    service: "Emergency",
    status: "PROBLEMATIC",
    flagged: true,
  },
  {
    id: "a3",
    createdAt: "2025-12-05",
    scheduledAt: "2025-12-12 09:00",
    city: "Medellín",
    clinicName: "Animalia Center",
    petOwnerName: "María Gómez",
    service: "Grooming",
    status: "COMPLETED",
    flagged: false,
  },
  {
    id: "a4",
    createdAt: "2025-12-11",
    scheduledAt: "2025-12-14 16:15",
    city: "Cali",
    clinicName: "CostaVet",
    petOwnerName: "Sebastián Ruiz",
    service: "Consultation",
    status: "PENDING",
    flagged: true,
  },
];
