import type { Pet } from "@/src/types/pets.types";

export const mockPets: Pet[] = [
  {
    id: "p1",
    name: "Luna",
    species: "DOG",
    breed: "Golden Retriever",
    ownerId: "u1",
    ownerName: "Ariana Barreto",
    ownerEmail: "ari@demo.com",
    city: "Barranquilla",
    createdAt: "2025-12-10",
    status: "ACTIVE",
  },
  {
    id: "p2",
    name: "Milo",
    species: "CAT",
    breed: "Criollo",
    ownerId: "u2",
    ownerName: "Carlos Pérez",
    ownerEmail: "carlos@demo.com",
    city: "Bogotá",
    createdAt: "2025-12-08",
    status: "ACTIVE",
  },
  {
    id: "p3",
    name: "Kira",
    species: "DOG",
    breed: "Pug",
    ownerId: "u3",
    ownerName: "María Gómez",
    ownerEmail: "maria@demo.com",
    city: "Medellín",
    createdAt: "2025-11-25",
    status: "ARCHIVED",
  },
  {
    id: "p4",
    name: "Toby",
    species: "OTHER",
    breed: "Conejo",
    ownerId: "u4",
    ownerName: "Sebastián Ruiz",
    ownerEmail: "sebas@demo.com",
    city: "Cali",
    createdAt: "2025-12-12",
    status: "ACTIVE",
  },
];
