// Datos de ejemplo
const mockClinics = [
  {
    id: 1,
    name: "Happy Paws Clinic",
    neighborhood: "El Prado",
    address: "Calle 45 # 23 - 10",
    phone: "3001234567",
    rating: 4.8,
    distance: "1.2 km",
    isOpen: true,
    is24Hours: false,
    services: ["Emergency", "Vaccination", "General Consultation"],
  },
  {
    id: 2,
    name: "AnimalCare 24H",
    neighborhood: "Riomar",
    address: "Cra 59 # 80 - 22",
    phone: "3019876543",
    rating: 4.5,
    distance: "2.5 km",
    isOpen: true,
    is24Hours: true,
    services: ["Emergency", "Surgery"],
  },
  {
    id: 3,
    name: "PetZone Veterinary Center",
    neighborhood: "Alameda del Río",
    address: "Transversal 9 # 110 - 35",
    phone: "3021239876",
    rating: 4.3,
    distance: "3.1 km",
    isOpen: false,
    is24Hours: false,
    services: ["General Consultation", "Vaccination"],
  },
  {
    id: 4,
    name: "Clinivet Express",
    neighborhood: "Boston",
    address: "Carrera 43 # 64 - 18",
    phone: "3055551234",
    rating: 4.9,
    distance: "900 m",
    isOpen: true,
    is24Hours: true,
    services: ["Emergency", "Home Visit", "General Consultation"],
  },
  {
    id: 5,
    name: "Mascotas & Salud",
    neighborhood: "Villa Santos",
    address: "Calle 85 # 24 - 50",
    phone: "3007778899",
    rating: 4.6,
    distance: "4.2 km",
    isOpen: false,
    is24Hours: false,
    services: ["Surgery", "Vaccination", "General Consultation"],
  },
  {
    id: 6,
    name: "VitalPet Barranquilla",
    neighborhood: "Los Andes",
    address: "Carrera 27 # 70 - 15",
    phone: "3045567890",
    rating: 4.7,
    distance: "2 km",
    isOpen: true,
    is24Hours: false,
    services: ["Emergency", "General Consultation", "Home Visit"],
  },
];

export const actiClinic = [
    {
    id: 1,
    name: "AnimalCare 24H",
    neighborhood: "Riomar",
    address: "Cra 59 # 80 - 22",
    phone: "3019876543",
    rating: 4.5,
    distance: "2.5 km",
    isOpen: true,
    is24Hours: true,
    services: ["Emergency", "Surgery"],
  },
  {
    id: 2,
    name: "Clinivet Express",
    neighborhood: "Boston",
    address: "Carrera 43 # 64 - 18",
    phone: "3055551234",
    rating: 4.9,
    distance: "900 m",
    isOpen: true,
    is24Hours: true,
    services: ["Emergency", "Home Visit", "General Consultation"],
  },
]

export default mockClinics